### ISSUE TITLE
javadoc.io link?

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/extensions#1016]
how about adding javadoc.io link ?

for neo4j it would be this to get latest version:
https://javadoc.io/doc/io.quarkiverse.neo4j/quarkus-neo4j

**Comment by holly-cummins** [comment]
Excellent thought!

**Comment by holly-cummins** [comment]
I thought this would be super-trivial, but I realised when I started writing it that javadoc.io has a page (returning 200) for everything in maven central. We don't want people excitedly clicking a "javadoc" link and then getting a page that says "there is no javadoc" so I've screened the contents before including the url. I've also cached, so that we don't hammer javadoc.io every build.

**Comment by holly-cummins** [comment]
The javadoc.io site does seem to be having so problems today; I don't know if those reliability issues happen often, or if I was just unlucky. They've got CloudFlare CDN, so I don't think a few builds from me could have triggered it. I hope.

<img width="1895" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/a63c16dd-1b1a-4a85-807a-d42a5daa90a8">

**Comment by maxandersen** [comment]
Why would there ever be no javadoc?

/max
https://about.me/maxandersen

**Comment by holly-cummins** [comment]
> Why would there ever be no javadoc? 

It happens reasonably often for the Quarkiverse extensions - see, for example, https://javadoc.io/doc/io.quarkiverse.amazonalexa/quarkus-amazon-alexa

<img width="1665" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/c54e474d-6354-42dc-9599-ff075919a604">

If the CI isn't publishing a javadoc jar to maven, there's no javadoc. And, in that case, we shouldn't display a link labelled 'javadoc', because anyone who clicks it will end up disappointed.

**Comment by holly-cummins** [comment]
That's now published. 

Example of extension without javadoc (so no link): https://quarkus.io/extensions/io.quarkiverse.amazonalexa/quarkus-amazon-alexa/
Example of extension with javadoc: https://quarkus.io/extensions/io.quarkiverse.azureservices/quarkus-azure-app-configuration/
