### ISSUE TITLE
Quarkus version dropdown is empty

### ISSUE THREAD

**Issue by gsmet** [quarkusio/extensions#103]
If not supported, maybe hide it?

![Screenshot from 2023-02-06 13-18-05](https://user-images.githubusercontent.com/1279749/216973200-44cb949d-4af6-4b7b-afeb-c44e4b50ba9c.png)

**Comment by holly-cummins** [comment]
I've found the root cause of this, which is that slashes are a *nuisance* when used with GraphQL and Javascript in combination. If a field name has slashes, it won't show up in GraphQL. Sometimes it will be converted to a field name with underscores, so I was assuming that was happening, but it wasn't happening everywhere, so the data was missing. I've avoided the whole issue by manually converting the field name to camel case. 

However, there's another issue, which is that the data I was trying to put into that dropdown isn't a great fit for the "Quarkus Version" header. I was putting in what version the extension was built with, and it should really be what version an extension is compatible with. Getting that information needs a bit of inference and reproducing logic from elsewhere, and in most cases can't just be read off the metadata (yet). So for the moment, I've kept the field we have, but renamed it to make the actual meaning clearer. I've raised #140 to cover getting the more useful information.
