### ISSUE TITLE
highlight maintainer of extension

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/extensions#18]
show the main lead or uploader of last release on the about page

**Comment by maxandersen** [comment]
Hmm. Sponsor isnt the same as maintainer?

**Comment by holly-cummins** [comment]
I agree the original intention of the work item has become a bit muddled because of the overlap/non-overlap between "sponsor" and "maintainer". Because this work item is cross-referenced in various places with the "sponsor" meaning, I propose we keep it marked as resolved, or it's just too confusing. I'll update the title of this work item to reflect the 'sponsor' interpretation. At least part of the goal of showing contributors and the scale of their contribution is covered by #297. There's an open question about whether we'd *also* want a field in the metadata sidebar showing the most active individual ... while we decide whether that's something we want, I'll close this, and we can open a new work item if we do want a field in the sidebar (or if we come up with another way of displaying the most active individual beyond what's in #297.)
