### ISSUE TITLE
Red Hatters missing in Red Hat part of contributors pie chart

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/extensions#443]
Red Hatters missing in Red Hat part of contributors pie chart

Sergey, Ozan, Franz, Aleš, Davide, mskacelik, Michael Edgar, Jiri Ondrusek are not in RH part of the chart but they are from RH

GH accounts: @sberyozkin @ozangunalp @franz1981 @alesj @DavideD @mskacelik @MikeEdgar @JiriOndrusek

https://quarkus.io/extensions/io.quarkus/quarkus-jdbc-mariadb/?tab=community

<img width="702" alt="Screenshot 2023-11-14 at 14 53 01" src="https://github.com/quarkusio/extensions/assets/925259/f7456270-4dc1-422b-b7dd-d480b3733661">

**Comment by sberyozkin** [comment]
@rsvoboda, Holly pointed it out too, I fixed mine on Thursday: https://github.com/sberyozkin, may be it needs to be refreshed here somehow ?

**Comment by holly-cummins** [comment]
Thanks, @rsvoboda! There are three categories of issues here: 

- Red Hatters who don't list Red Hat in their profile. This is @franz1981, @alesj, @DavideD, @mskacelik, @JiriOndrusek, @ozangunalp.  
- Red Hatters who list Red Hat, but it's mixed in with other information, such as 'Red Hat @hibernate'. We have a bunch of different variations, and I try to normalise these, but I can see I didn't correctly handle what @MikeEdgar has listed (`Red Hat, @xlate`)
- Stale data. That is, Red Hatters who didn't list Red Hat last week but now do this week, but the site hasn't updated. We cache the GitHub data because we can only pull down a relatively small amount per hour before getting hit by a rate limiter. So in general there will be some lag. I cache some information, including company affiliation, for a few days. This is made worse because https://github.com/quarkiverse/quarkus-qute-web/issues/55 has broken the extensions site build since the weekend, so even without caching, the site wouldn't be updated. It looks like this is only @sberyozkin at the moment. 

I'll do #207 now, which should mean https://github.com/quarkiverse/quarkus-qute-web/issues/55 doesn't block the build, and @sberyozkin should show in the right segment. I'll also handle the comma case, which should fix Mike.

**Comment by holly-cummins** [comment]
A build has gone through, and @sberyozkin is now showing correctly - see, for example, https://quarkus.io/extensions/io.quarkus/quarkus-smallrye-jwt/?tab=community

**Comment by alesj** [comment]
>> Red Hatters who don't list Red Hat in their profile.

@holly-cummins how do I add this?
Just by adding `Red Hat` to my current `Coder, father, cyclist, ...` ?

**Comment by holly-cummins** [comment]
> > > Red Hatters who don't list Red Hat in their profile.
> 
> @holly-cummins how do I add this? Just by adding `Red Hat` to my current `Coder, father, cyclist, ...` ?

There's a dedicated field in the profile for company affiliation. It's the one with the little building picture:

<img width="170" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/18ae91e1-d8a3-4692-b8bc-0aa11cff91c7">

So instead of "@mood funky backend", which is the current value for @alesj, it needs to be something like "@RedHatOfficial" or "Red Hat" or "Red Hat Inc" even something like "Red Hat - @mood funky backend" should work. The more extra stuff in there, the more chance my name-normalisation breaks, but I try to handle most typical cases. @rsvoboda's was a bit complex but I made it work. :) If there's something you want and it doesn't show as Red Hat let me know and I can add another rule for parsing it.

**Comment by rsvoboda** [comment]
> @rsvoboda's was a bit complex but I made it work. :) 

👍 🥳 🎉

**Comment by holly-cummins** [comment]
I've corrected @MikeEdgar's case, although it may take a few days to show in the UI, because of caching. Apart from that, and telling people (which you've kindly done, @rsvoboda ), I don't think there's anything more we can do, so closing as half-fixed-half-won't-fix. :) 

Let me know if you disagree and think we should do more, @rsvoboda.

**Comment by rsvoboda** [comment]
I'm fine with this.
