### ISSUE TITLE
Version missing on front page for some extensions

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/extensions#69]
For example:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/11509290/214300781-6bf86b9d-9cb4-4152-be1f-63aa921e8fa7.png">

The version is present on the details page (eg https://quarkus.io/extensions.quarkus.io/io.quarkiverse.operatorsdk/quarkus-operator-sdk-bundle-generator). I suspect the issue happens when the category is missing, but that shouldn't stop the version display. It might be an over-zealous guard, or it could be an exception is happening and halting the display logic.

**Comment by metacosm** [comment]
Note that the bundle extension metadata was wrong before 5.0.3. That was fixed in https://github.com/quarkiverse/quarkus-operator-sdk/pull/494. While the `categories` stanza existed, it wasn't set at the proper indentation level and was therefore probably ignored. The version (and first category) now shows up as of 5.0.3 presumably because the `categories` field was fixed.

**Comment by holly-cummins** [comment]
This turned out to be a copy and paste error; we had code which literally said “only show the version if the category is present.” A few other extensions were affected. 

Before:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/11509290/223409217-2818ba6b-2383-4739-b7ed-c6abd47993d4.png">

After: 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/11509290/223409654-3b0f083d-03df-4b27-a060-2ae4b4c413a9.png">
